### ISSUE TITLE
Low Accuracy on Indoor3DSeg Dataset

### ISSUE THREAD

**Issue by ShilinC** [erikwijmans/Pointnet2_PyTorch#9]
Hi! Could you include your trained model & accuracy on these two datasets? 

I tried the default configuration on Indoor3DSemSeg using MSG. However, the accuracy is pretty low (~0.33) on test set. Could you let me know if this is not a full implementation or I just missed something? 

Thanks!

**Comment by erikwijmans** [comment]
Definitely seems like something is being missed.  I am getting a test-set accuracy of ~0.73 after the first epoch.

**Comment by erikwijmans** [comment]
I used the master branch.  The 0.4.0 branch is my slow more effort to port the current implementation to the new way to implement custom cuda in pytorch.

**Comment by ShilinC** [comment]
Hi! Did you use the default configuration?

I didn't change the code and after training 200 epochs, the best loss is 0.5756 for sem_seg_checkpoint and 0.3424 for sem_seg_best

Are these numbers comparable to yours?

**Comment by erikwijmans** [comment]
Yep, I used the default numbers.  Loss is not the same thing as accuracy, and those loss numbers seem great and comparable to what I am seeing.

This repo has fallen out of sync with my pytorch utils repo and it doesn't look like the accuracy number is getting displayed anywhere.  I will quickly update this repo so at least those numbers are being displayed on visdom.

**Comment by erikwijmans** [comment]
I brought this repo inline with my pytorch utils repo.  I have been relying entirely on visdom for my model tracking as of late, so the trainer in my pytorch utils repo no longer prints anything to the console.  This will let you see the model's progress in visdom at least.

**Comment by ShilinC** [comment]
Traceback (most recent call last):
  File "train_sem_seg.py", line 114, in <module>
    lr_scheduler = lr_sched.LambdaLR(optimizer, lr_lbmd)
  File "/home/shilin/anaconda3/envs/PyTorch_Py3/lib/python3.6/site-packages/torch/optim/lr_scheduler.py", line 91, in __init__
    super(LambdaLR, self).__init__(optimizer, last_epoch)
  File "/home/shilin/anaconda3/envs/PyTorch_Py3/lib/python3.6/site-packages/torch/optim/lr_scheduler.py", line 22, in __init__
    self.step(last_epoch + 1)
  File "/home/shilin/anaconda3/envs/PyTorch_Py3/lib/python3.6/site-packages/torch/optim/lr_scheduler.py", line 55, in step
    for param_group, lr in zip(self.optimizer.param_groups, self.get_lr()):
  File "/home/shilin/anaconda3/envs/PyTorch_Py3/lib/python3.6/site-packages/torch/optim/lr_scheduler.py", line 95, in get_lr
    for lmbda, base_lr in zip(self.lr_lambdas, self.base_lrs)]
  File "/home/shilin/anaconda3/envs/PyTorch_Py3/lib/python3.6/site-packages/torch/optim/lr_scheduler.py", line 95, in <listcomp>
    for lmbda, base_lr in zip(self.lr_lambdas, self.base_lrs)]
  File "train_sem_seg.py", line 110, in <lambda>
    lr_lbmd = lambda e: max(args.lr_decay**(int(it * args.batch_size / args.decay_step)), lr_clip / args.lr)
NameError: name 'it' is not defined

**Comment by erikwijmans** [comment]
Fixed.

**Comment by ShilinC** [comment]
You may want to change 
start_epoch, best_loss = pt_utils.load_checkpoint
to
_, start_epoch, best_loss = pt_utils.load_checkpoint
since the first returned by load_checkpoint is 'it'

I also change the last line to print the test error:
test_err, _ = trainer.eval_epoch(test_loader)

But if I feed the trained model to trainer.eval_epoch() I still get around 0.33 accuracy. Maybe something is wrong in trainer.eval_epoch()? My best losses match yours.

**Comment by ShilinC** [comment]
Hi! One more question: if my own input point cloud contains only XYZ thus is BxNx3 instead of BxNx9, should I just set 'input_channels = 0' as:

model = Pointnet(num_classes=input_classes, input_channels=0, use_xyz=True)?

**Comment by erikwijmans** [comment]
Yep

**Comment by tonysy** [comment]
@ShilinC  Hi, did you get the similar performance with the original paper? I only get ~81% acc on segmentation.
